#+title: Metodo de Numerov
#+author: Rafael Obed Egurrola Corella
#+setupfile: ~/uni/latex.org
#+startup: latexpreview

* Método de Numerov

Método numérico desarrollado por el astrónomo ruso Boris Vasilyevich Numerov en la década de 1910. Se basa en desarrollar la expansión de Taylor de una función \( y : I \subset \mathbb{R} \to \mathbb{R} \) alrededor de un punto \( x_0 \in I \), donde \( y \) es solución a la ecuación diferencial de segundo orden

\[ y''(x) = - g(x)y(x) + s(x), \]

con \( g: I \to \mathbb{R} \) y \( s: I \to \mathbb{R} \) como funciones conocidas, definidas en el mismo intervalo \( I \) que \( y \). Para que la expansión de Taylor sea válida hasta el orden requerido, se exige que \( y \) sea al menos \( C^4 \) i.e. cuatro veces diferenciable. Además, \( g \) y \( s \) deben ser funciones suficientemente suaves e.g. continuas, para garantizar la existencia de una solución.

El método de Numerov sigue un esquema de diferencias finitas, por lo que comenzamos con una expansión de Taylor, a quinto órden. Para un paso adelante \( (x= x_{0} + \Delta x) \) y un paso atrás \( (x=x_{0} - \Delta x) \), se tiene

\[ y(x_{0} + \Delta x ) = y(x_{0}) + y'(x_{0})\Delta x + \frac{y''(x_{0})}{2!} \Delta x^2 + \frac{y'''(x_{0})}{3!}\Delta x^3 + \frac{y^{(4)}(x_{0})}{4!}\Delta x^4 + \frac{y^{(5)}(x_0)}{5!} + \order{\Delta x^6}, \]

\[ y(x_{0} - \Delta x ) = y(x_{0}) - y'(x_{0})\Delta x + \frac{y''(x_{0})}{2!} \Delta x^2 - \frac{y'''(x_{0})}{3!}\Delta x^3 + \frac{y^{(4)}(x_{0})}{4!}\Delta x^4 - \frac{y^{(5)}(x_0)}{5!} + \order{\Delta x^6}. \]

Se define una malla uniforme \( x_n = x_0 + n\Delta x \) y se denota:

+ \( y(x_n) \equiv y_n \) (valores de la funcion en puntos de la malla).
+ \( y(x_n \pm \Delta x) \equiv y_{n \pm 1} \) (puntos adyacentes).

Así, las expansiones se reescriben como:

\[ y_{n+1} = y_n + y_n' \Delta x + \frac{1}{2} y_n'' (\Delta x)^2 + \frac{1}{6} y_n''' (\Delta x)^3 + \frac{1}{24} y_n^{(4)} (\Delta x)^4 + \frac{1}{120} y_n^{(5)} (\Delta x)^5 + \order{\Delta x^6} \]

\[ y_{n-1} = y_n - y_n' \Delta x + \frac{1}{2} y_n'' (\Delta x)^2 - \frac{1}{6} y_n''' (\Delta x)^3 + \frac{1}{24} y_n^{(4)} (\Delta x)^4 - \frac{1}{120} y_n^{(5)} (\Delta x)^5 + \order{\Delta x^6} \]

Al sumar ambos desarrollos se obtiene

\[ y_{n+1} + y_{n-1} = 2y_n + y_n''(\Delta x)^2 + \frac{1}{12} y_n^{(4)} (\Delta x)^4 + \mathcal{O} [(\Delta x)^6] \]

Luego, se puede escribir

\[ z_n \equiv y'' = - g_ny_n + s_n, \]

y aplicamos la expresion obtenida

\[ z_{n+1} + z_{n-1} = 2z_n + z_n'' (\Delta x)^2 + \mathcal{O}[(\Delta x)^4] \]

Esta es una expresion para la segunda derivada desarrollando en Taylor hasta tercer orden, de modo que, ademas, se obtiene una expresion para la cuarta derivada \( y^{(4)} \)

\[ z''_n = \frac{z_{n+1}+z_{n-1}-2z_n}{(\Delta x)^2} + \mathcal{O}[(\Delta x)^2] = y_n^{(4)}. \]

sustituyendo en la expresion

\[ y_{n+1} + y_{n-1} = 2y_n + y_n''(\Delta x)^2 + \frac{1}{12} y_n^{(4)} (\Delta x)^4 + \mathcal{O} [(\Delta x)^6] \]

se obtiene la formula de Numerov

 \begin{align*}
  &y_{n+1} = 2y_n - y_{n-1} + (z_n)(\Delta x)^2 + \frac{1}{12}(z_{n+1}+z_{n-1}-2z_n)(\Delta x)^2 + \order{(\Delta x)^6} \\
  &y_{n+1} =  2y_n -y_{n-1} + (-g_ny_n + s_n) (\Delta x)^2 + \frac{1}{12} [(-g_{n+1}y_{n+1}+s_{n+1}) \\
  & \qq{}\qq{} +(-g_{n-1}y_{n-1}+s_{n-1})-2(-g_ny_n+s_n)](\Delta x)^2 + \order{(\Delta x)^6} \\
  &y_{n+1}\qty[1 + \frac{1}{12}g_{n+1}(\Delta x)^2] = 2y_n \qty[1+\qty(\frac{-g_n}{2}+\frac{g_n}{12})(\Delta x)^2] \\
  & \qq{}\qq{} - y_{n-1}\qty[1+\frac{1}{12}g_{n-1}(\Delta x)^2] + \frac{1}{12}(s_{n+1}+10s_n+s_{n-1})(\Delta x)^2 + \order{(\Delta x)^6} \\
  &y_{n+1}\qty[1 + \frac{1}{12}g_{n+1}(\Delta x)^2] = 2y_n \qty[1-\frac{5}{12}g_n(\Delta x)^2] \\
  & \qq{}\qq{} -y_{n-1}\qty[1+\frac{1}{12}g_{n-1}(\Delta x)^2] + \frac{1}{12}(s_{n+1}+10s_n+s_{n-1})(\Delta x)^2 + \order{(\Delta x)^6}.
\end{align*}

Esta expresion nos permite propagar la solucion \( y_n \) conociendo los primeros dos valores \( y_0  \) y \( y_1 \). Las ecuaciones que se van a resolver por medio de esta formula tienen \( s(x)=0 \). Luego, podemos simplificar la formula por medio de la cantidad

  \[ f_n \equiv 1 + \frac{1}{12}g_n(\Delta x)^2, \]

  haciendo

  \begin{align*}
      f_n - 1 &= \frac{1}{12}g_n(\Delta x)^2 \\
      1-5(f_n -1) &= 1-\frac{5}{12}g_n(\Delta x)^2 \\
      6-5f_n &= 1-\frac{5}{12}g_n(\Delta x)^2 \\
      12-10f_n &= 2\qty(1-\frac{5}{12})g_n(\Delta x)^2
  \end{align*}

  se reescribe la formula de Numerov

  \begin{equation}
  \label{eq:numerov}
      \boxed{y_{n+1} = \frac{(12-10f_n)y_n-f_{n-1}y_{n-1}}{f_{n+1}}}
  \end{equation}



* Ecuación de Schrödinger unidimensional, independiente del tiempo

 \[ \frac{\partial^{2}\psi}{\partial x^2} = - \frac{2m}{\hbar^2}(E - V(x))\psi \]

** Oscilador Harmonico

Un sistema de oscilador armonico es cuando el potencial tiene la forma

\[ V(x) = - \frac{1}{2}K x^2. \]

El desarrollo se simplifica en gran medida al hacer el cambio a unidades adimensionales:

+ Variable adimensional \( \xi \)
+ Esta variable se relaciona con \( x \) por medio de la longitud \( \lambda \) de modo que \( x = \lambda \xi \)

\[ \pdv[2]{\psi}{(\lambda \xi)} = \qty( - \frac{2m E }{\hbar^2} + \frac{mK \lambda^2}{\hbar^2} \xi^2  )\psi \]

\[ \pdv[2]{\psi}{\xi} = \qty( - \frac{2m E \lambda^{2}}{\hbar^2} + \frac{mK \lambda^4}{\hbar^2} \xi^2  )\psi \]

+ Hacemos \( mK\lambda^4 /\hbar^2 = 1 \), de donde

  \[ \lambda = (\hbar^2/mK)^{1/4} \]

+ Relacionamos la frecuencia angular del oscilador con la constante de fuerza

  \[ \omega = \sqrt{\frac{K}{m}} \implies K = m\omega^2 \]

+ La variable adimensional queda

  \[ \lambda\xi = x \implies \xi=\qty(\frac{mK}{\hbar^2})^{1/4} x = \qty(\frac{m \omega}{\hbar})^{1/2} x  \]

+ Introducimos la energia adimensional \( \epsilon \)

  \[ \epsilon = \frac{2E}{\hbar \omega} \]

+ Sustituyendo estas expresiones en la ecuacion de Schrödinger

  \[ \pdv[2]{\psi}{\xi} = \qty( - \frac{2m E \lambda^{2}}{\hbar^2} + \frac{mK \lambda^4}{\hbar^2} \xi^2  )\psi \]

  \[ \pdv[2]{\psi}{\xi} = \qty( - \frac{2m (\epsilon \hbar \omega/2) (\hbar^2/m^2\omega^2)^{1/2}}{\hbar^2} +  \xi^2  )\psi \]

+ Finalmente la ecuacion de Schrödinger adimensional que se resuelve con el metodo de Numerov es:

  \begin{equation}
  \label{eq:ho}
  \boxed{\pdv[2]{\psi}{\xi} = (\epsilon - \xi^2)\psi}
  \end{equation}


* Implementacion



#+begin_src python

e_lower = np.min(vpot)
e_upper = np.max(vpot)

#+end_src


* Central Potentials

\[ H = \qty[ - \frac{\hbar^2}{2m}\nabla^2 + V(r)] \]

** Radial equaiton

asdd

La probabilidad \( p(r) \dd{r} \) de encontrar a una particula a una distancia entre \( r \) y \( r + \dd{r} \) del centro esta dada por la integracion sobre solamente las variables angulares del cuadrado de la funcion de onda

\[ p(r) \dd{r} = \int_{\Omega} |\psi_{nlm}(r,\theta,\phi)|^2 r \dd{\theta}r\sin\theta\dd{\phi} \dd{r} = |R_{nl}|^2 r^2 \dd{r} = |\chi_{nl}|^2 \dd{r}  \]

donde introducimos la funcion auxiliar \( \chi(r) \), que se conoce como funcion de onda orbital

\[ \chi(r) = rR(r) \]

como consecuencia de la normalizacion de los harmonicos esfericos

\[ \int_0^{2\pi} \dd{\phi} \int_0^{\pi}\dd{\theta}|Y_{lm}(\theta,\phi|^2 \sin\theta = 1, \]

la condicion de normalizacion para \( \chi \) es

\[ \int_0^{\infty} | \chi_{nl}(r)|^2 \dd{r} = 1. \]

Esto significa que la funcion \( |\chi(r)|^2 \) se puede interpretar directamente como la densidad de probabilidad radial. Entonces escribimos la ecuacion radial para \( \chi(r) \) en vez de para \( R(r) \)

\begin{equation}
\label{eq:schr-rad}
- \frac{\hbar^2}{2m}\dv[2]{\chi}{r} + \qty[V(r) + \frac{\hbar^2 l (l+1)}{2mr^2} - E] \chi(r) = 0
\end{equation}

esta es la forma de la ecuacion de Schrodinger unidimensional para una particula bajo un potencial efectivo

\[ \hat{V}(r) = V(r) + \frac{\hbar^2 l(l+1)}{2mr^2} \]

** Potencial de Coulomb


** Malla Logaritmica

\[ x = x(r) \]

La relacion entre la malla con paso constante \( \Delta x \) y la malla de paso variable esta dada por

\[ \Delta x  = x'(r) \Delta r \]

La malla logaritmica toma la forma

\[ x(r) \equiv \ln(\frac{Zr}{a_0}) \]

y se obtiene

\[ \Delta x = \frac{\Delta r}{r} \]

La razon \( \Delta r / r \) se mantiene constante en la malla de \( r \). Al transformar la ecuacion \ref{eq:schr-rad} en la nueva variable \( x \)

+ Expresando las derivadas con respecto a \( r \) en terminos de derivadas con respecto a \( x \). Dado que:

  \[ x = \ln(\frac{Zr}{a_0}) \implies r = \frac{a_0}{Z}e^x \]

+ La primera derivada de \( \chi \) con respecto a \( r \) es

  \[ \dv{\chi}{r} = \dv{\chi}{x}\cdot \dv{x}{r} \]

  luego

  \begin{align*}
      \dv{x}{r} &= \dv{r}\ln(\frac{Zr}{a_0}) = \frac{1}{r} \\
      \dv{\chi}{r} &= \frac{1}{r} \dv{\chi}{x} \\
      \dv[2]{\chi}{r} &= \frac{1}{r^2} \dv{\chi}{x} + \frac{1}{r}\dv{r}(\dv{\chi}{x}) \\
      \dv{r}(\dv{\chi}{x}) &= \dv[2]{\chi}{x} \cdot \dv{x}{r} = \frac{1}{r} \dv[2]{\chi}{x} \\
      \dv[2]{\chi}{x} &= - \frac{1}{r^2}\dv{\chi}{x} + \frac{1}{r^2}\dv[2]{\chi}{x} = \frac{1}{r^2}\qty(\dv[2]{\chi}{x} - \dv{\chi}{x})
  \end{align*}

+ Sustituyendo en la ecuacion \ref{eq:schr-rad}

  \begin{align*}
  &- \frac{\hbar^2}{2m} \frac{1}{r^2} \qty(\dv[2]{\chi}{x}-\dv{\chi}{x}) + \qty[V(r) + \frac{\hbar^2 l(l+1)}{2mr^2} - E r^2]\chi = 0 \\
  &- \frac{\hbar^2}{2m}\qty(\dv[2]{\chi}{x}-\dv{\chi}{x}) + \qty[V(r) r^2 + \frac{\hbar^2 l(l+1)}{2m} - E r^2]\chi = 0 \\
  &- \frac{\hbar^2}{2m}\dv[2]{\chi}{x} + \frac{\hbar^2}{2m}\dv{\chi}{x} + \qty[V(r)r^2 + \frac{\hbar^2 l(l+1)}{2m}-Er^2]\chi = 0
  \end{align*}

+ Expresando \( r \) en terminos de \( x \)

  \[ - \frac{\hbar^2}{2m}\dv[2]{\chi}{x} + \frac{\hbar^2}{2m}\dv{\chi}{x} + \qty[V\qty(\frac{a_0}{Z}e^x)\qty(\frac{a_0}{Z})^2 e^{2x} + \frac{\hbar^2l(l+1)}{2m}- E\qty(\frac{a_0}{Z})^2e^{2x}]\chi = 0 \]

+ En esta ecuacion aparece un termino de la primera derivada

  \[ \frac{\hbar^2}{2m} \dv{\chi}{x} \]

  en consecuencia, no se pueden utilizar los metodos de integracion convencionales para esta ecuacion.

Para obtener una ecuacion que se pueda integrar sobre una malla logaritmica, tenemos que hacer la transformacion

\[ y(x) = \frac{1}{\sqrt{r}}\chi(r(x)) \]

\[ \dv[2]{y}{x} + \qty[\frac{2m_e}{\hbar^2}r^2(E-V(r)) - \qty(l + \frac{1}{2})^2]y(x) = 0 \]
